name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Version
        run: mvn --settings .github/workflows/m2settings.xml versions:set -DnewVersion=${GITHUB_REF/refs\/tags\/v/} -DgenerateBackupPoms=false
      - name: Release
        run: |
          mvn --settings .github/workflows/m2settings.xml clean deploy
        env:
          LOG_LEVEL: FATAL
          BINTRAY_API_USERNAME: ${{ secrets.BINTRAY_API_USERNAME }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}